### ISSUE TITLE
Panic During Concurrent Download

### ISSUE THREAD

**Issue by tri-adam** [sylabs/scs-library-client#129]
In testing, I encountered a `panic` in the client, with the following abbreviated trace:

```
panic: runtime error: index out of range [1] with length 1 [recovered]
        panic: runtime error: index out of range [1] with length 1

goroutine 64 [running]:
testing.tRunner.func1.2({0xba7320, 0xc00001e060})
        /usr/local/go/src/testing/testing.go:1209 +0x24e
testing.tRunner.func1()
        /usr/local/go/src/testing/testing.go:1212 +0x218
panic({0xba7320, 0xc00001e060})
        /usr/local/go/src/runtime/panic.go:1038 +0x215
github.com/sylabs/scs-library-client/client.getContentLength({0xd8a528, 0xc0001aa000}, {0xc000306000, 0xc0002baa20})
        /home/adam/go/pkg/mod/github.com/sylabs/scs-library-client@v1.2.1/client/pull.go:178 +0x28e
github.com/sylabs/scs-library-client/client.(*Client).ConcurrentDownloadImage(0xc00045e440, {0xd8a528, 0xc0001aa000}, 0x40eff4, {0x0, 0x0}, {0xbf2cfb, 0x5}, {0xbf20e1, 0x3}, ...)
        /home/adam/go/pkg/mod/github.com/sylabs/scs-library-client@v1.2.1/client/pull.go:286 +0x8cd
```

This occurs at this point in the code:

https://github.com/sylabs/scs-library-client/blob/2e30d58f8a9212b4a35946eb62d42f1e84140f0c/client/pull.go#L177-L178

Upon quick inspection, it looks to me like this code assumes that the `Content-Range` header is set, and that it has at least one `/` in its value. If either of these conditions are not met, the code will `panic`.

**Comment by EmmEff** [comment]
Resolved in v1.4.0
