### ISSUE TITLE
V2 push uses large amounts of RAM, can fail

### ISSUE THREAD

**Issue by dctrud** [sylabs/scs-library-client#60]
Noted a push of a 575MB container failing on a Pi4 with 2GB RAM:

```
10:22 pm $ singularity push -U objects_pair1_arm.sif library://dtrudg-sylabs/default/objectdetection:objects-arm-pair1
WARNING: Skipping container verifying
 256.00 MiB / 575.75 MiB [================================================================>---------------------------------------------------------------------------------]  44.46% 60.78 MiB/sruntime: out of memory: cannot allocate 1073741824-byte block (1081507840 in use)
fatal error: out of memory
```

Observed during a successful push on machine with 48GB RAM that the resident size of `singularity` reaches a full 2GB:

```
17264 dave      20   0 4598220 *2.089g*  20048 S   0.3  4.4   0:05.49 singularity
```

This appears to be because the `v2` push uses `go-retryablehttp` which is doing a `ReadAll` if passed simple `bytes.Reader` or `io.Reader` so it can rewind to resend data on retries:

https://github.com/hashicorp/go-retryablehttp/blob/9e058b6ea276c805e329c57ba4f15c67463b31a6/client.go#L163

Passing in an io.ReadSeeker seems like it would avoid this excessive memory usage.

**Comment by dctrud** [comment]
GC Debug with stack trace:
```
$  GODEBUG=gctrace=1 singularity push -U objects_pair1_arm.sif library://dtrudg-sylabs/default/objectdetection:objects-arm-pair1
gc 1 @0.317s 0%: 0.029+1.7+0.018 ms clock, 0.11+0/1.2/3.0+0.072 ms cpu, 4->4->0 MB, 5 MB goal, 4 P
gc 2 @0.388s 0%: 0.033+1.8+0.022 ms clock, 0.13+0.30/1.5/3.6+0.089 ms cpu, 4->4->1 MB, 5 MB goal, 4 P
gc 3 @0.450s 0%: 0.040+2.0+0.018 ms clock, 0.16+0.32/1.5/3.7+0.074 ms cpu, 4->4->1 MB, 5 MB goal, 4 P
WARNING: Skipping container verifying
 0 B / 575.75 MiB [---------------------------------------------------------------------------------------------------------------------------------------------------------------------]   0.00%gc 4 @17.638s 0%: 0.042+8.0+0.029 ms clock, 0.16+1.1/6.7/7.6+0.11 ms cpu, 4->4->2 MB, 5 MB goal, 4 P
gc 5 @17.666s 0%: 0.030+15+0.037 ms clock, 0.12+0/3.7/19+0.15 ms cpu, 8->8->7 MB, 9 MB goal, 4 P
gc 6 @17.699s 0%: 0.030+29+0.033 ms clock, 0.12+0/3.0/35+0.13 ms cpu, 15->15->13 MB, 16 MB goal, 4 P
gc 7 @17.746s 0%: 0.025+24+0.024 ms clock, 0.10+0/1.7/27+0.098 ms cpu, 29->29->25 MB, 30 MB goal, 4 P
 16.00 MiB / 575.75 MiB [===>----------------------------------------------------------------------------------------------------------------------------------------]   2.78% 79.63 MiB/s 00m06sgc 8 @17.804s 0%: 0.018+46+0.022 ms clock, 0.074+0/1.7/49+0.091 ms cpu, 57->57->49 MB, 58 MB goal, 4 P
gc 9 @17.917s 0%: 0.024+88+0.019 ms clock, 0.096+0/2.1/91+0.077 ms cpu, 113->113->97 MB, 114 MB goal, 4 P
 64.00 MiB / 575.75 MiB [===============>---------------------------------------------------------------------------------------------------------------------------]  11.12% 106.32 MiB/s 00m04sgc 10 @18.139s 0%: 0.026+174+0.024 ms clock, 0.10+0/1.4/177+0.098 ms cpu, 225->225->193 MB, 226 MB goal, 4 P
 128.00 MiB / 575.75 MiB [==============================>-----------------------------------------------------------------------------------------------------------]  22.23% 106.36 MiB/s 00m03sgc 11 @18.573s 0%: 0.027+347+0.026 ms clock, 0.11+0/1.6/351+0.10 ms cpu, 449->449->385 MB, 450 MB goal, 4 P
 256.00 MiB / 575.75 MiB [=============================================================>----------------------------------------------------------------------------]  44.46% 127.65 MiB/s 00m01sgc 12 @19.315s 0%: 0.031+514+0.026 ms clock, 0.12+0/2.0/518+0.10 ms cpu, 897->897->769 MB, 898 MB goal, 4 P
 256.00 MiB / 575.75 MiB [=============================================================>-----------------------------------------------------------------------------]  44.46% 91.19 MiB/s 00m01sruntime: out of memory: cannot allocate 1073741824-byte block (1081540608 in use)
fatal error: out of memory

runtime stack:
runtime.throw(0xcdf3fc, 0xd)
	/opt/go/src/runtime/panic.go:617 +0x5c
runtime.largeAlloc(0x3ffffe00, 0x2430101, 0x24000e0)
	/opt/go/src/runtime/malloc.go:1057 +0x140
runtime.mallocgc.func1()
	/opt/go/src/runtime/malloc.go:950 +0x38
runtime.systemstack(0x152)
	/opt/go/src/runtime/asm_arm.s:354 +0x84
runtime.mstart()
	/opt/go/src/runtime/proc.go:1153

goroutine 1 [running]:
runtime.systemstack_switch()
	/opt/go/src/runtime/asm_arm.s:298 +0x4 fp=0x27058b8 sp=0x27058b4 pc=0x418eac
runtime.mallocgc(0x3ffffe00, 0xc02880, 0x91ab01, 0x2705938)
	/opt/go/src/runtime/malloc.go:949 +0x8c4 fp=0x270591c sp=0x27058b8 pc=0x3ca55c
runtime.makeslice(0xc02880, 0x3ffffe00, 0x3ffffe00, 0x2476ee0)
	/opt/go/src/runtime/slice.go:49 +0x70 fp=0x2705930 sp=0x270591c pc=0x404db0
bytes.makeSlice(0x3ffffe00, 0x0, 0x0, 0x0)
	/opt/go/src/bytes/buffer.go:232 +0x58 fp=0x2705944 sp=0x2705930 pc=0x46d134
bytes.(*Buffer).grow(0x27059c4, 0x200, 0x10000000)
	/opt/go/src/bytes/buffer.go:145 +0x150 fp=0x2705968 sp=0x2705944 pc=0x46ca9c
bytes.(*Buffer).ReadFrom(0x27059c4, 0xe55a48, 0x25cf3b0, 0x0, 0xe40e85, 0xa6144268, 0xa6b6ff3b)
	/opt/go/src/bytes/buffer.go:205 +0x48 fp=0x27059a4 sp=0x2705968 pc=0x46cf2c
io/ioutil.readAll(0xe55a48, 0x25cf3b0, 0x200, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/opt/go/src/io/ioutil/ioutil.go:36 +0xd0 fp=0x27059d8 sp=0x27059a4 pc=0x55dd58
io/ioutil.ReadAll(...)
	/opt/go/src/io/ioutil/ioutil.go:45
github.com/hashicorp/go-retryablehttp.NewRequest(0xcd3783, 0x3, 0x256a1c0, 0x1ae, 0xc3d9b8, 0x25cf3b0, 0x0, 0x2746a00, 0x1e6)
	vendor/github.com/hashicorp/go-retryablehttp/client.go:185 +0x4b4 fp=0x2705a60 sp=0x27059d8 pc=0x82a514
github.com/sylabs/scs-library-client/client.(*Client).postFileV2(0x2490d80, 0xe5e2f0, 0x2490f80, 0xe55f10, 0x248c978, 0x23fc0190, 0x0, 0x24945c0, 0x18, 0xe5ccd0, ...)
	vendor/github.com/sylabs/scs-library-client/client/push.go:280 +0x334 fp=0x2705b34 sp=0x2705a60 pc=0x8340c0
github.com/sylabs/scs-library-client/client.(*Client).UploadImage(0x2490d80, 0xe5e2f0, 0x2490f80, 0xe59768, 0x248c978, 0x25b8000, 0x25, 0xcd3858, 0x3, 0x248c970, ...)
	vendor/github.com/sylabs/scs-library-client/client/push.go:176 +0x100c fp=0x2705cec sp=0x2705b34 pc=0x833418
github.com/sylabs/singularity/internal/app/singularity.LibraryPush(0xbeadd1e3, 0x15, 0xbeadd1f9, 0x41, 0x281e000, 0x234, 0x267c0e0, 0x19, 0x26f8140, 0x16, ...)
	internal/app/singularity/push.go:106 +0x734 fp=0x2705df8 sp=0x2705cec pc=0xb31b8c
github.com/sylabs/singularity/cmd/internal/cli.glob..func48(0x1423020, 0x2802fc0, 0x2, 0x3)
	cmd/internal/cli/push.go:78 +0x10c fp=0x2705e74 sp=0x2705df8 pc=0xb5ab78
github.com/spf13/cobra.(*Command).execute(0x1423020, 0x249a010, 0x3, 0x4, 0x1423020, 0x249a010)
	vendor/github.com/spf13/cobra/command.go:830 +0x204 fp=0x2705ee4 sp=0x2705e74 pc=0x5ae32c
github.com/spf13/cobra.(*Command).ExecuteC(0x1423de0, 0xd, 0x2593f8c, 0x4)
	vendor/github.com/spf13/cobra/command.go:914 +0x234 fp=0x2705f4c sp=0x2705ee4 pc=0x5aec84
github.com/sylabs/singularity/cmd/internal/cli.ExecuteSingularity()
	cmd/internal/cli/singularity.go:246 +0x118 fp=0x2705fc0 sp=0x2705f4c pc=0xb526f8
main.main()
	cmd/singularity/cli.go:17 +0x14 fp=0x2705fc4 sp=0x2705fc0 pc=0xb5e640
runtime.main()
	/opt/go/src/runtime/proc.go:200 +0x204 fp=0x2705fe4 sp=0x2705fc4 pc=0x3efc74
runtime.goexit()
	/opt/go/src/runtime/asm_arm.s:868 +0x4 fp=0x2705fe4 sp=0x2705fe4 pc=0x41ad08

goroutine 19 [syscall]:
os/signal.signal_recv(0x0)
	/opt/go/src/runtime/sigqueue.go:139 +0x130
os/signal.loop()
	/opt/go/src/os/signal/signal_unix.go:23 +0x14
created by os/signal.init.0
	/opt/go/src/os/signal/signal_unix.go:29 +0x30

goroutine 25 [IO wait]:
internal/poll.runtime_pollWait(0xa61c4f3c, 0x72, 0xffffffff)
	/opt/go/src/runtime/netpoll.go:182 +0x48
internal/poll.(*pollDesc).wait(0x2710d84, 0x72, 0xe00, 0xe96, 0xffffffff)
	/opt/go/src/internal/poll/fd_poll_runtime.go:87 +0x80
internal/poll.(*pollDesc).waitRead(...)
	/opt/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0x2710d70, 0x2882000, 0xe96, 0xe96, 0x0, 0x0, 0x0)
	/opt/go/src/internal/poll/fd_unix.go:169 +0x184
net.(*netFD).Read(0x2710d70, 0x2882000, 0xe96, 0xe96, 0x3c0128, 0x3c9f70, 0x3ca820)
	/opt/go/src/net/fd_unix.go:202 +0x38
net.(*conn).Read(0x2774200, 0x2882000, 0xe96, 0xe96, 0x0, 0x0, 0x0)
	/opt/go/src/net/net.go:177 +0x5c
crypto/tls.(*atLeastReader).Read(0x2810050, 0x2882000, 0xe96, 0xe96, 0x3c6ffc, 0x744970, 0xe55cd0)
	/opt/go/src/crypto/tls/conn.go:761 +0x78
bytes.(*Buffer).ReadFrom(0x286c160, 0xe54ed8, 0x2810050, 0x8, 0x743344, 0xc2a698, 0xcbbfb8)
	/opt/go/src/bytes/buffer.go:207 +0xac
crypto/tls.(*Conn).readFromUntil(0x286c000, 0xe55cd0, 0x2774200, 0x5, 0x2774200, 0xb6d7db60)
	/opt/go/src/crypto/tls/conn.go:783 +0xd8
crypto/tls.(*Conn).readRecordOrCCS(0x286c000, 0xd37e00, 0x286c0b0, 0x24000e0)
	/opt/go/src/crypto/tls/conn.go:590 +0x108
crypto/tls.(*Conn).readRecord(...)
	/opt/go/src/crypto/tls/conn.go:558
crypto/tls.(*Conn).Read(0x286c000, 0x2883000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/opt/go/src/crypto/tls/conn.go:1236 +0x140
net/http.(*persistConn).Read(0x2816140, 0x2883000, 0x1000, 0x1000, 0x7dd34c, 0x278e000, 0x2452e28)
	/opt/go/src/net/http/transport.go:1524 +0x1c0
bufio.(*Reader).fill(0x283d950)
	/opt/go/src/bufio/bufio.go:100 +0x114
bufio.(*Reader).Peek(0x283d950, 0x1, 0x0, 0x0, 0x1, 0x278e200, 0x0)
	/opt/go/src/bufio/bufio.go:138 +0x38
net/http.(*persistConn).readLoop(0x2816140)
	/opt/go/src/net/http/transport.go:1677 +0x168
created by net/http.(*Transport).dialConn
	/opt/go/src/net/http/transport.go:1357 +0x924

goroutine 26 [select]:
net/http.(*persistConn).writeLoop(0x2816140)
	/opt/go/src/net/http/transport.go:1976 +0xb8
created by net/http.(*Transport).dialConn
	/opt/go/src/net/http/transport.go:1358 +0x940

goroutine 40 [IO wait]:
internal/poll.runtime_pollWait(0xa61c4e34, 0x72, 0xffffffff)
	/opt/go/src/runtime/netpoll.go:182 +0x48
internal/poll.(*pollDesc).wait(0x285d194, 0x72, 0xe00, 0xe92, 0xffffffff)
	/opt/go/src/internal/poll/fd_poll_runtime.go:87 +0x80
internal/poll.(*pollDesc).waitRead(...)
	/opt/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0x285d180, 0x2912000, 0xe92, 0xe92, 0x0, 0x0, 0x0)
	/opt/go/src/internal/poll/fd_unix.go:169 +0x184
net.(*netFD).Read(0x285d180, 0x2912000, 0xe92, 0xe92, 0x8, 0x3c9f70, 0x3ca820)
	/opt/go/src/net/fd_unix.go:202 +0x38
net.(*conn).Read(0x2413ca0, 0x2912000, 0xe92, 0xe92, 0x0, 0x0, 0x0)
	/opt/go/src/net/net.go:177 +0x5c
crypto/tls.(*atLeastReader).Read(0x25cf310, 0x2912000, 0xe92, 0xe92, 0x3c6ffc, 0x744970, 0xe55cd0)
	/opt/go/src/crypto/tls/conn.go:761 +0x78
bytes.(*Buffer).ReadFrom(0x24be160, 0xe54ed8, 0x25cf310, 0xc9b3a8, 0x743344, 0xc2a698, 0xcbbfb8)
	/opt/go/src/bytes/buffer.go:207 +0xac
crypto/tls.(*Conn).readFromUntil(0x24be000, 0xe55cd0, 0x2413ca0, 0x5, 0x2413ca0, 0x275e1e0)
	/opt/go/src/crypto/tls/conn.go:783 +0xd8
crypto/tls.(*Conn).readRecordOrCCS(0x24be000, 0xd37e00, 0x24be0b0, 0x24000e0)
	/opt/go/src/crypto/tls/conn.go:590 +0x108
crypto/tls.(*Conn).readRecord(...)
	/opt/go/src/crypto/tls/conn.go:558
crypto/tls.(*Conn).Read(0x24be000, 0x2913000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/opt/go/src/crypto/tls/conn.go:1236 +0x140
net/http.(*persistConn).Read(0x24cc320, 0x2913000, 0x1000, 0x1000, 0x7dd34c, 0x278e740, 0x2652e28)
	/opt/go/src/net/http/transport.go:1524 +0x1c0
bufio.(*Reader).fill(0x26ccd50)
	/opt/go/src/bufio/bufio.go:100 +0x114
bufio.(*Reader).Peek(0x26ccd50, 0x1, 0x0, 0x0, 0x1, 0x2828200, 0x0)
	/opt/go/src/bufio/bufio.go:138 +0x38
net/http.(*persistConn).readLoop(0x24cc320)
	/opt/go/src/net/http/transport.go:1677 +0x168
created by net/http.(*Transport).dialConn
	/opt/go/src/net/http/transport.go:1357 +0x924

goroutine 42 [select]:
gopkg.in/cheggaaa/pb%2ev1.(*ProgressBar).refresher(0x2476ee0)
	vendor/gopkg.in/cheggaaa/pb.v1/pb.go:493 +0xa4
created by gopkg.in/cheggaaa/pb%2ev1.(*ProgressBar).Start
	vendor/gopkg.in/cheggaaa/pb.v1/pb.go:124 +0xd8

goroutine 41 [select]:
net/http.(*persistConn).writeLoop(0x24cc320)
	/opt/go/src/net/http/transport.go:1976 +0xb8
created by net/http.(*Transport).dialConn
	/opt/go/src/net/http/transport.go:1358 +0x940
```
